# -*- coding: utf-8 -*-
{
    'name': 'BSC - forwardERP - Beacukai',
    'version': '10',  
    'category': 'Custom',
    'author':'BSC',
    'description' : """Odoo Beacukai""",
    'depends': ['base','product','stock','purchase','account','sale','mrp'],
    'sequence': 20,
    'qweb':[
     # "static/src/xml/qweb.xml",
     ],
    'demo': [
        'data/ref_api_type.xml',
        'data/ref_mode_transport.xml',
        'data/ref_negara.xml',
        'data/ref_destination_tpb.xml',
        'data/ref_code_id.xml',
    ],
    'data': [
        'views/report_bc23.xml',                 
        'views/beacukai_view.xml',
        'views/product_view.xml',
        'views/purchase_view.xml',
        'views/mrp_production_views.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/stock_picking_view.xml',
        'views/account_invoice_view.xml',
        'views/sale_view.xml',
        'wizard/laporan_pemasukan_bc_23.xml',
        'wizard/create_bc_incoming_wizard_view.xml',  
        'wizard/excel_laporan_mutasi_view.xml',
        'wizard/excel_laporan_pertanggungjawaban_bahan_baku_view.xml',
        'wizard/excel_laporan_pertanggungjawaban_barang_jadi_view.xml',       
        'wizard/excel_laporan_pertanggungjawaban_mesin_view.xml',
        'wizard/excel_laporan_pertanggungjawaban_reject_view.xml',
        'wizard/wizard_laporan_mutasi_view.xml',
        'wizard/laporan_posisi_view.xml',
        'wizard/excel_laporan_konversi_pemakaian_bahan_view.xml',      
        'wizard/trigger_onchange_mrp_view.xml',
        'data/ir_sequence.xml',
        'data/default_data.xml',
        'data/base_data.xml',
        'data/mail_template_data.xml',
        'wizard/salesperson_report_view.xml',
        'views/sales_report_report.xml',
        'views/report_salesperson.xml',           
        'views/bc_report_posisi.xml',           
        'views/bc_report_outgoing.xml',
        'views/bc_report_incoming.xml',
        'views/bc_report_wip.xml',
        'views/cctv_view.xml',           
        # 'views/bc_config_view.xml',      
        'views/laporan_mutasi.xml',
        'views/bc_2_3_view.xml',      
        'views/menu.xml',
        'views/tpb_goods_tariff.xml',
        'views/tpb_document.xml',
        'views/tpb_container.xml',
        'views/tpb_package.xml',
        'views/partner_view.xml',          
        'views/res_users_views.xml',
        'data/bsc_setting_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
