# -*- coding: utf-8 -*-
{
    'name': 'BSC - forwardERP - Beacukai (Samuel)',
    'version': '10',  
    'category': 'Custom',
    'author':'BSC',
    'description' : """Odoo Beacukai""",    
    'depends': ['web', 'v10_bsc_beacukai', 'v10_bsc_beacukai_mixin'],
    'data': [        
        'views/beacukai_outgoing_25_view.xml',
        'views/beacukai_outgoing_27_view.xml',
        'views/beacukai_outgoing_261_view.xml',
        'views/beacukai_outgoing_30_view.xml',
        'views/beacukai_outgoing_41_view.xml',
        'views/beacukai_incoming_262_view.xml',
        'views/beacukai_incoming_27_view.xml',
        'views/beacukai_incoming_40_view.xml',
        'views/input_registration_wizard.xml',
        'views/stock_picking_views.xml',
        'views/purchase_view.xml',
        'views/laporan_mutasi.xml',
        'views/menu.xml',
        'views/asset.xml',
        'wizard/add_purchase_view.xml',
        'security/ir.model.access.csv', 
        'data/ir_sequence.xml',
        'data/res_lang.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
