{
    'name': 'Forwarderp PWK',    
    'category': 'Custom',
    'author' :'Alfius Samuel Sutopo',        
    'depends' : [
                 'base', 
                 'product',
                 'account',
                 'sale',
                 'vit_efaktur',
                 'sale_management',
                 'report_xlsx',
                ],
    'data': [             
             'security/ir_rule.xml',             
             'wizard/generate_rpb_view.xml',
             'wizard/generate_rpm_view.xml',   
             'wizard/generate_packing_list_view.xml',          
             'views/pwk_view.xml',
             'views/packing_list_view.xml',
             'views/menu.xml',
             'views/no1_mutasi_veneer_basah_view.xml',
             'views/no2_mutasi_veneer_rolerdryer_view.xml',
             'views/no3_mutasi_veneer_klindry_view.xml',
             'views/no4_mutasi_veneer_kering_view.xml',
             'views/no5_mutasi_barecore_view.xml',
             'views/no6_mutasi_veneer_unrepair_view.xml',
             'views/no7_mutasi_veneer_ok_repair_view.xml',
             'views/no8_mutasi_veneer_gs_view.xml',
             'views/no8_pemakaian_veneer_gs_view.xml',
             'views/no9_mutasi_assembling_finishing_view.xml',
             'views/no10_mutasi_sf_grading_view.xml',
             'views/no11_mutasi_harian_grading_view.xml',
             'views/no12_mutasi_harian_pmg_view.xml',
             'views/sale_view.xml',
             'views/purchase_view.xml',
             'views/payment_report.xml',
             'views/cash_report.xml',
             'views/receipt_report.xml',
             'views/pph_report.xml',
             'wizard/payment_report_view.xml',
             'wizard/receipt_report_view.xml',
             'wizard/cash_report_view.xml',
             'wizard/pph_report_view.xml',
             'wizard/rekap_purchase_order_bahan_baku_view.xml',
             'wizard/peb_report_wizard_view.xml',
             'wizard/stuffing_report_wizard_view.xml',
             'wizard/log_report_wizard_view.xml',             
             'views/report_packing_list_local.xml',
             'views/report_packing_list_export.xml',
             'views/report_packing_list_waste.xml',
             'views/report_packing_list_produksi.xml',
             'views/report_packing_list_produksi2.xml',
             'views/report_invoice_export.xml',
             'views/report_invoice_local.xml',
             'views/report_invoice_waste.xml',
             'views/report_credit_note.xml',
             'views/report_debit_note.xml',
             'views/report_credit_note_en.xml',
             'views/report_debit_note_en.xml',
             'views/report_account_move.xml',
             'views/report_account_payment.xml',
             'views/report_sale_order.xml',
             'views/report_lampiran_sale_order.xml',
             'views/report_sale_contract.xml',
             'views/report_purchase_order_jasa.xml',
             'views/report_purchase_order_bahan_baku.xml',
             'views/report_purchase_order_bahan_penolong.xml',
             'views/report_purchase_order_rotary.xml',
             'views/report_payment_note.xml',
             'views/report_nota_perusahaan.xml',
             'views/report_daftar_kayu_olahan.xml',
             'views/report_nota_pembelian_jenis_kayu.xml',
             'views/rekap_purchase_order_bahan_baku.xml',
             'security/ir.model.access.csv',             
             ],
             
    'installable': True,
    'application': True,
    'auto_install': False,
}
